feat: add option to install all components at init
emulsify-ds/emulsify-cli pull request #101
Opened 2022-02-25 15:01 UTC by ryanhagerty

**Summary**

This PR fixes/implements the following:

- Adds option to install all default system components at the start

**How to review this PR**
- [ ] Pull this branch down, run `npm build` and `npm link`
- [ ] Create a new Drupal project somewhere. I used `composer create-project drupal/recommended-project drupal-folder`
- [ ] Go into that folder and run `npm link @emulsify/cli` (make sure there are no warnings/errors)
- [ ] Run `emulsify init "Theme Name"`. You'll see a new option listed that allows an individual to install all components instead of just the default (screen shot below)
- [ ] Install all the components. `emulsify system install compound --all`. To verify, you can go to your theme directory and checkout the components. For example, the `card` is not a default component. 

![Screen Shot 2022-02-25 at 9 57 20 AM](https://user-images.githubusercontent.com/8405274/155737427-2a94fc51-d920-41b4-8cc3-2ec649e0e90f.png)

**Closing issues**
Closes #11

2022-03-18 03:03 UTC, patrickocoffeyo requested changes
Hey @ryanhagerty! I left a couple of comments here, but overall this looks great!

2022-03-18 03:03 UTC, patrickocoffeyo commented on USAGE.md
> +If you would like to simply install all components available within the system you've selected, use the `--all` flag.
Nice catch! :smile:

2022-03-18 03:22 UTC, patrickocoffeyo commented
One more quick note... do you think it'd make sense to document the new `--all` parameter in the [usage md](https://github.com/emulsify-ds/emulsify-cli/blob/develop/USAGE.md#system)?

2022-04-22 12:57 UTC, ryanhagerty commented
@patrickocoffeyo Thanks for the review! Comments addressed.

2022-04-22 17:50 UTC, patrickocoffeyo approved these changes
@ryanhagerty LGTM, nice!! :raised_hands:

2022-04-25 11:52 UTC, merged