Subtheme
emulsify-ds/emulsify-cli pull request #130
Opened 2022-05-28 13:17 UTC by fertant

**Summary**

This PR fixes/implements the following **bugs/features**

- Bug 1
- Bug 2
- Feature 1
- Feature 2
- Breaking changes

Explain the **motivation** for making this change. What existing problem does the pull request solve?

**Documentation Update (required)**

If this pull request requires a change to Emulsify documentation, those changes, updates, and/or new information must accompany this pull request.

**How to review this PR**

- [ ] Step 1
- [ ] Step 2
- [ ] Step 3: Profit

**Closing issues**

Closes #

2022-07-02 14:02 UTC, fertant commented
"subtheme" tag in emulsify component configuration marking component that belongs to different subthemes. That creates the new possibility to pull all components that belong to a certain subtheme. The main theme that could be built separately from Drupal will contain pagers from different websites and be marked with subtheme tags for different sites. Each smaller site could pull all required components based on the tag with single command even during the CD process. Like,
`emulsify component install -s landing`
The list of components that will be installed by this command for the current theme is:
landing-pages
text
grid
cta
links
card
buttons
images

This PR creates an additional command option to pull subtheme.

2022-07-12 14:22 UTC, amazingrando commented
@fertant Please fill out the details on what this PR does and how to review it and I'll get this added to our team's queue for review. Thanks!

2022-07-18 11:32 UTC, ModulesUnraveled requested changes

2022-07-30 11:42 UTC, fertant commented on src/index.ts
> +  )
I totally agree with it. Parameters renamed to componentSet

2022-10-04 21:29 UTC, fertant commented
Are there any updates for this PR? Do you planning to merge it or someone has more questions to proposed updates?
@ModulesUnraveled

2026-06-12 20:31 UTC, closed without merging