2.x Prep and base
emulsify-ds/emulsify-cli pull request #278
Opened 2024-06-17 14:34 UTC by mikeethedude

## Summary

This is where we are starting for 2.x Here are some of the thigs we need to accomplish in this branch.

- [ ] Remove eslint
- [ ] Update or remove chalk
- [ ] Migrate or rebuild as a module type package
- [ ] Update testing requirements
- [ ] Improve Help Text
- [ ] Init command should be interactive instead of failing with missing parameters.

## Documentation update (required)

If this pull request requires a change to Emulsify documentation, those changes, updates, and/or new information must accompany this pull request.

## How to review this pull request

- [ ] Step 1
- [ ] Step 2
- [ ] Step 3: Profit

## Closing issues

Closes #

2024-09-03 17:46 UTC, mikeethedude commented
Holy cow this was hard to get committed. I had to ignore these tests for now. We must clean these up before this is ready:
init.test.ts log.test.ts jsonSchemaToTs.test.ts getInitSuccessMessageForPlatform.test.ts getPlatformInfo.test.ts getAvailableStarters.test.ts

2024-09-27 14:27 UTC, joetower reviewed
@mikeethedude Should I be able to run: 
`emulsify component install blockquote --force`

And have it, or any other component (https://github.com/emulsify-ds/emulsify-ui-kit/tree/main/src/components) I list, install successfully? 

I tried installing the blockquote and I get no feedback

![Screenshot from 2024-09-27 09-25-52](https://github.com/user-attachments/assets/aa4b3195-d56b-49cf-9266-8d2f06eb6325)

2024-09-27 15:20 UTC, mikeethedude commented
> @mikeethedude Should I be able to run: `emulsify component install blockquote --force`
> 
> And have it, or any other component (https://github.com/emulsify-ds/emulsify-ui-kit/tree/main/src/components) I list, install successfully?
> 
> I tried installing the blockquote and I get no feedback
> 
> ![Screenshot from 2024-09-27 09-25-52](https://private-user-images.githubusercontent.com/366413/371570696-aa4b3195-d56b-49cf-9266-8d2f06eb6325.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0NTA2ODUsIm5iZiI6MTcyNzQ1MDM4NSwicGF0aCI6Ii8zNjY0MTMvMzcxNTcwNjk2LWFhNGIzMTk1LWQ1NmItNDljZi05MjY2LThkMmYwNmViNjMyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyN1QxNTE5NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NzA4OWFlZjJmYjExOGZkOGM5ZmEyNjAwMWE3MmEwOTUxOGEwMjZjNDYwZDRiZDY0NzEzYTkzNTMyNzkxYjUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ju-m7-fU1TSyuaHI1QkWXiv9UNtdfL-e8DOAVEy2haI)

@joetower Only if that is defined here: https://github.com/emulsify-ds/emulsify-ui-kit/blob/main/system.emulsify.json
@robherba We should probably change the output to something helpful if we can't find the definition for that component.

2024-09-27 15:33 UTC, joetower commented
@mikeethedude Okay, thank you! 

The thing is, in testing this, those three already exist, which, I suppose is why the `--force` is needed. So, to properly test I should check the contents of `text` before running `emulsify component install text --force` and then after?

2024-09-27 15:42 UTC, mikeethedude commented
Yeah you can try and remove that component or otherwise mess it up to see if that puts the right one in.

2024-09-27 17:41 UTC, joetower commented
@mikeethedude Thank you! I removed `text` and tried to re-install and this is what the cli returned

![Screenshot from 2024-09-27 12-40-38](https://github.com/user-attachments/assets/b0da634f-4d76-4913-a196-1c7c718a0bc9)

Note: it _did_ add the `text` component, but also returned an unexpected `links` mention

2024-09-27 17:42 UTC, joetower commented
@mikeethedude But, if I remove it again and run it with `--force` it _does_ what you'd expect. 

![Screenshot from 2024-09-27 12-42-24](https://github.com/user-attachments/assets/ce42fd2a-24d2-4ace-b2b7-5b181857666d)

2024-09-27 17:47 UTC, mikeethedude commented
I believe that lines up with the expectations though I think it should be okay with a dependency existing. Maybe we should have it ask if you want to replace the dependency when it already exists? The red text is also probably a little strong there.

This is good feedback, thank you!

2024-09-27 17:50 UTC, joetower approved these changes
@mikeethedude This tests as you've outlined. Super excited about this release and what will come next. :+1:

2024-12-13 20:57 UTC, robherba approved these changes

2026-04-12 23:14 UTC, mariannuar requested changes
@robherba Most of it looks and works as expected. But when I tried to run the command to add a component that already exists, I got these messages:

<img width="740" height="234" alt="Image" src="https://github.com/user-attachments/assets/bf652f44-869d-469b-b680-bcae34bb9143" />

2026-04-16 04:36 UTC, robherba commented
Hi @mariannuar, thanks for your feedback. This behavior is correct.
When you run `emulsify component install accordion` with `--force`, it overrides the existing component without asking for confirmation.

If you run `emulsify component install accordion` without `--force`, the CLI tells you the component already exists and asks n/Y if you want to replace it.

The `button`, `icons`, and `typography` are dependencies of the `accordion` component. That is why you see those messages. The CLI installs the component and its dependencies, asking one by one if you want to override them in case they already exist.

<img width="953" height="246" alt="image" src="https://github.com/user-attachments/assets/81b9d1c9-0483-4b64-8141-0859cc45a0c2" />

2026-04-16 04:57 UTC, robherba commented
However, I agree that these messages are not very clear, so I have adjusted them to make it easier for the end user to understand what is happening and what action they should take. Please let me know if this makes sense.

<img width="907" height="193" alt="image" src="https://github.com/user-attachments/assets/49c9134e-b89c-4db4-b5f8-0fc6f0503d73" />

2026-04-16 06:18 UTC, robherba commented
I also fixed an issue I found when creating components with multi-word names, e.g.:

`emulsify component create featuredItem`

Could you please run the preview, start Storybook, and validate that the component works without errors?

<img width="1677" height="629" alt="image" src="https://github.com/user-attachments/assets/80839408-dc13-415b-896c-105f8bf945b9" />

2026-04-16 15:11 UTC, mariannuar approved these changes
@robherba Thank you so much for the new changes. LGTM! :shipit:

2026-04-22 04:19 UTC, merged